# This is a basic workflow to help you get started with Actions

name: CI-Testing-Actions
env:                                                    #Stexcel
  APPLICATION_NAME : "MyTest"                           #global  
  DEPLOY_PACKAGE_NAME : "deploy-ver-${{github.sha}}"    #environment

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a jobs called my_testing, my_deploy"
  my_testing:
    runs-on: ubuntu-latest
   
    steps: 
      - name: Pront Hello World message inTesting
        run: echo "Hello, world! from testing"
        
      - name: Execute few commands
        run: |
          echo "Hello message1"
          echo "Hello Message2"
          echo "Aplication name: ${{env.APPLICATION_NAME }}"
      
#       - name: Git clon my repo              # Cloning git files 
#         uses: actions/checkout@v1           # into virtualmachine
        
#       - name: List current folder           # Check files
#         run: ls -la                         # In directory
      
      
        
  my_deploy:
    runs-on: windows-latest
    needs: [my_testing]                                # hertov jobsere run linelu command
    
#     env:                                              # Job 
#       VAR1: "This is Job Level Variable1"             # level
#       VAR2: "This is Job Level Variable1"             # variables
      

    steps:
    
#       - name: Print env vars
#         run: |                                         # Job
#           echo "Var1  = ${{env.Var1}}"                 # level
#           echo "Var2  = ${{env.Var2}}"                 # variables
#           #echo "Var3  = $LOCAL_VAR"
#         env:
#           LOCAL_VAR: "This is Super local Environment variable"
      
      - name: Pront Hello World message in deploy
        run: echo "Hello, world! from deployment"
        
      - name : Printing Deployment packege
        run : echo "Deploy packge name is $ {{env.DEPLOY_PACKAGE_NAME}}"
